# Generated by Django 4.1.3 on 2023-01-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instalaciones', '0002_instalacion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacion',
            name='status',
            field=models.CharField(choices=[(0, 'Pendiente'), (1, 'Asignada'), (2, 'Completada')], max_length=10, verbose_name='Estado de la instlación'),
        ),
    ]
