# Generated by Django 4.1.3 on 2023-01-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instalaciones', '0005_alter_instalacion_status_alter_instalacion_tecnico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='dia_asignado',
            field=models.DateField(blank=True, null=True, verbose_name='Día asignado'),
        ),
    ]
